language: cpp

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
     - unzip
     - nasm 
     - makeself
     - pkg-config
     - fuse
     - libfuse-dev
     - libwxgtk3.0-dev
     - wx-common
     - wx3.0-headers

compiler:
 - gcc

script: 
 - #cd /tmp
 - #wget https://github.com/wxWidgets/wxWidgets/releases/download/v3.0.2/wxWidgets-3.0.2.zip
 - #mkdir -p /home/travis/wxWidgets-3.0.2
 - #cd /home/travis/wxWidgets-3.0.2
 - #cp /tmp/wxWidgets-3.0.2.zip .
 - #unzip wxWidgets-3.0.2.zip
 - cd /home/travis/build/ka7/VeraCrypt/src/
 - #make WXSTATIC=1 WX_ROOT=/home/travis/wxWidgets-3.0.2 wxbuild
 - make 
 - sudo sh /home/travis/build/ka7/VeraCrypt/src/Setup/Linux/veracrypt*

branches:
  only:
    - travis_build
